version: '3.7'
services:
  app:
    container_name: app
    build: .
    restart: always
    volumes:
      - ./report-info:/report-info
    ports:
      - "8080:8080"
    depends_on:
      - db
    command: sh -c './wait-for db:5432 -- npm start'
  db:
    container_name: db
    image: 'postgres:15-alpine'
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres