spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    baseline-on-migrate: true

jwt:
  secret:
    key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

api:
  version: 1.0-SNAPSHOT
  title: My REST API